### ISSUE TITLE
Handling localhost Certificate error

### ISSUE THREAD

**Issue by alexleonard** [MichMich/laravel-mandrill#7]
I noticed that any localhost development failed to send any messages, just returning false.

If I changed the return from False to 

```
// catch errors
if (curl_errno($ch))
{
    $errors = curl_error($ch);
    curl_close($ch);
    return $errors;
}
```

Then I received the following error:
error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed

I found the following blog post:

http://www.mixedwaves.com/2010/06/making-php-curl-request-to-https-url/

So I downloaded [this cacert.pem file](http://curl.haxx.se/ca/cacert.pem) and updated the request function to this:

```
// setup curl request
$ch = curl_init();

if (Request::env() == 'local')
{
    curl_setopt ($ch, CURLOPT_CAINFO, dirname(__FILE__)."/cacert.pem");
}
```

This sorted my issue and sending notifications now works from my local machine.

I'm not sure if this is a guaranteed behaviour type that could be anticipated for all local development environments, but I thought I'd post about it here in case this is useful to someone.

Cheers,
Alex

**Comment by alexleonard** [comment]
Looks like this is likely a local issue that affects certain setups and can also be cleared by running:

curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, 0);
curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, 0);

**Comment by mariusnegrean** [comment]
great work!

**Comment by mariusnegrean** [comment]
I got the status "Sent" , but i see no email. Do you have some ideas ?

**Comment by alexleonard** [comment]
I haven't tried sending mailouts via the API (is that what you're trying to do?)

**Comment by mariusnegrean** [comment]
Finally i managed to send emails, the issue was the api_key. If I created a "Test Key" the emails had a big big latency, but with a normal key, everything fine. Congrats for the good work!
Best regards.
